[package]
name = "ical_rust"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.6.1"
log = "0.4.14"
thiserror = "1.0.30"
either = "1.6.1"
