[package]
name = "ical_rust"
version = "0.6.0"

edition = "2024"
description = "A lightweight, efficient, and robust iCalendar (ics) parser and recurrence expander library"
license = "MIT"
repository = "https://github.com/MindFlavor/ical_rust"
homepage = "https://github.com/MindFlavor/ical_rust"
readme = "README.md"
keywords = ["icalendar", "ics", "parser", "rrule", "scheduling"]
categories = ["parser-implementations", "date-and-time"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.44"
chrono-tz = "0.10"
log = "0.4.30"
thiserror = "2.0"
either = "1.16"
